version: '3.9'

services:
  ambaari:
    container_name: ambaari-management
    image: ambaari:1.8
    environment:
      - DB_HOST=${PROD_DB_HOST}
      - DB_USER=${PROD_DB_USER}
      - DB_PASSWORD=${PROD_DB_PASSWORD}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - internal
    ports:
      - 3000:3000

networks:
  internal:
