import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import { PlusOutlined } from "@ant-design/icons";
import { DatePicker, Calendar, Button, Modal, Input } from "antd";
import { withAuthenticator } from "@aws-amplify/ui-react";

const Home = ({ signOut, user }: { signOut: any; user: any }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const showModal = () => {
    setIsModalOpen(true);
  };

  const handleOk = () => {
    setIsModalOpen(false);
  };

  const handleCancel = () => {
    setIsModalOpen(false);
  };

  const { Search } = Input;

  const onSearch = (value: string) => console.log(value);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button
          type="primary"
          danger
          onClick={signOut}
          style={{ alignSelf: "flex-end" }}
        >
          Sign Out
        </Button>
        <h4 className={styles.title}>
          Hi {user.attributes?.given_name}, Welcome to{" "}
          <h1>Ambaari Web Portal</h1>
        </h4>
        <Button
          type="primary"
          icon={<PlusOutlined />}
          size="large"
          onClick={showModal}
          style={{ alignSelf: "flex-center" }}
        >
          Add Event
        </Button>
        <Modal
          title="Event Info"
          open={isModalOpen}
          onOk={handleOk}
          onCancel={handleCancel}
        >
          <Search
            placeholder="Mobile No"
            allowClear
            enterButton="Find"
            size="large"
            onSearch={onSearch}
            style={{ marginTop: "2em" }}
          />
          <Input
            placeholder="Alternate Mobile No:"
            size="large"
            style={{ marginTop: "2em" }}
          />
          <Input placeholder="Name" size="large" style={{ marginTop: "2em" }} />
          <Input
            placeholder="Email Address"
            size="large"
            style={{ marginTop: "2em" }}
          />
          <Input
            placeholder="Postal Address"
            size="large"
            style={{ marginTop: "2em" }}
          />
          <Input
            placeholder="Event Type"
            size="large"
            style={{ marginTop: "2em" }}
          />
          <DatePicker.RangePicker
            size="large"
            showTime
            use12Hours
            format={"DD/MM/YY h:mm a"}
            showNow
            minuteStep={30}
            style={{ width: "100%", marginTop: "2em" }}
          />
        </Modal>
        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}

        <Calendar />
      </main>
      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
};

export default withAuthenticator(Home);
